version: 1.0.0-rc{build}
image: Visual Studio 2017

branches:
  only:
  - feature/continuos-integration

configuration: Release
skip_tags: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
environment:
  # this is how to set encrypted variable. Go to "Encrypt data" page in account menu to encrypt data.
  # Token of code coverage coveralls .io
  COVERALLS_REPO_TOKEN:
    secure: gecEXs9g2ETz7YkDrGCdc/Z9YqqNokGdoldPzy5zxwMYGdDGCkDG8cMLQr9KejYB

before_build:
- cmd: nuget restore RabbitMQ.Abstraction.sln

build:
  project: RabbitMQ.Abstraction.sln
  publish_nuget: true
  include_nuget_references: true 
  publish_nuget_symbols: true
  parallel: true
  verbosity: minimal

after_build:
- ps: msbuild RabbitMQ.Abstraction.sln /t:pack /p:Configuration=Release --include-source

artifacts:
- path: '**\Stone.RabbitMQ.Abstraction*.nupkg'
  name: NuGet

test: off

test_script:
- ps: dotnet test .\RabbitMQ.Abstraction.Tests\RabbitMQ.Abstraction.Tests.csproj --filter "FullyQualifiedName~UnitTests" --configuration Release

after_test:
# Coveralls.io and OpenCover integration
- ps: C:\Users\$($env:UserName)\.nuget\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[RabbitMQ.Abstraction]RabbitMQ.Abstraction*" -target:"C:\Users\$($env:UserName)\.nuget\packages\xunit.runner.console\2.2.0\tools\xunit.console.exe" "-targetargs:RabbitMQ.Abstraction.Tests\bin\Debug\RabbitMQ.Abstraction.Tests.dll" -output:coverage.xml
- ps: C:\Users\$($env:UserName)\.nuget\packages\coveralls.net\0.7.0\tools\csmacnz.Coveralls.exe --opencover coverage.xml -r %COVERALLS_REPO_TOKEN%

#deploy:
#- provider: NuGet
#  api_key:
    # GitHub trocar pelo da conta da stone
#    secure: yVnwQrFVedb/RyaiSlhL0rlb5S1A+ICdsIBKzUlAgPqGOxF3XfxZIrJ21bWFMIRd
#  artifact: /Stone.RabbitMQ.Abstraction.*\.nupkg/
#  on:
#    branch: master

#- provider: GitHub
#  release: Stable $(appveyor_build_version)
#  description: "Versão estável do client"
#  auth_token:
    # GitHub trocar pelo da conta da stone
#    secure: EJCiUbMZOzdu1xi1+9GgprukVKCbCqbhrHH24IjRIzG96NGG2u3WNSBd93wKXflg
#  artifact: /Stone.RabbitMQ.Abstraction.*\.nupkg/
#  on:
#    branch: master